### ISSUE TITLE
Published Pages associated with purged accounts are still published

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#300]
Not sure if only at usegalaxy.org or not.

At least two accounts that have been completely purged still have "published pages"

One was removed today and anonymized (inappropriate content). The other was removed last June, not anonymized (clear spam).

@dannon is this something you could help with? See: https://usegalaxy.org/pages/list_published

**Comment by dannon** [comment]
@jennaj Should be fixed now; no code error but there was an old cached page there we had to regenerate.

**Comment by jennaj** [comment]
@dannon I'm still seeing the pages at usegalaxy.org. is there a PR we can link back here to track change until hits the server? Not sure I understand the fix or what to do to view the update. Thanks!

**Comment by dannon** [comment]
@jennaj I closed this out thinking of a completely separate issue.  I'll take a look.

**Comment by jennaj** [comment]
gentle ping @dannon

**Comment by dannon** [comment]
@jennaj Thanks for the nudge, and, sorry!  Fixed in #10106.

**Comment by jennaj** [comment]
Note: retest at usegalaxy.org after 20.09 is released

Ref: https://github.com/galaxyproject/galaxy/milestone/17

**Comment by jennaj** [comment]
Fixed! Wasn't right after 20.09 went on main, but must have cleared out by now with the data cleanup processes :)

Thanks!
